### ISSUE TITLE
Measuring Point

### ISSUE THREAD

**Issue by Eysvr** [crowdmodeling20ss/exercise1#27]
A possible implementation:

Adding the visited path in every pedestrian tick (inside the while loop). This way every cell that has been visited will be held. I also advise keeping the cellular model tick count so that if a pedestrian has stepped into any measuring cell, we will know the number of cells that they have visited in how many ticks.

This can be implemented by creating an iter. var in simulation which holds the number of ticks that is passed all the way down to the pedestrians' tick function. In the pedestrians' tick function, we will append to the total path [position_x, position_y, iteration_num]. This can be a separate list than the total path that we have now if it will break the methods that use total_path.

Also, the reason for using the visited path is we don't have to calculate during the simulation. We can just write it to a file and then calculate it after the scenario.

When calculating it we must also remember that we only hold the center position, so we can calculate the measuring point coordinates and its vicinity so that if the center is any of these cells, it means that a pedestrians at least one cell have gotten into the measuring point.

The only thing to do at a measuring point is, when we find a point that is inside measuring point we need to find the last point that is inside measuring point; later take the number of cells that has been visited before and divide by the iteration number that we now have which shows us at which cellular model tick the pedestrian left the measuring point.
Then divide that path by tick. That gives us the average speed until it gets out of the measuring point.

**Comment by farukcankaya** [comment]
It is implemented in #29
